### ISSUE TITLE
Remove default text color

### ISSUE THREAD

**Issue by LeonManolo** [Fingertips18/scroll-wheel-date-picker#2]
https://github.com/Fingertips18/scroll-wheel-date-picker/blob/7c95c1f0ed25947b341f86d646ee1bb51b7bf29a/lib/src/constants/theme_constants.dart#L20

Just a really small change :).
The default text color is white even in light mode. By removing this line the text takes the default app theme text color and it looks perfect in dark and light mode.

**Comment by fingertips18** [comment]
@LeonManolo  I forgot to make the `textStyle` optional. I created an update, and it is now fixed.
